language: ruby
rvm:
#   - "1.9.3"
  - "2.0.0"
#   - jruby-19mode # JRuby in 1.9 mode
#   - rbx-19mode
before_install:
  - gem install hoe rake-compiler;
  - sudo apt-get install xpra xserver-xorg-video-dummy freeglut3-dev;
before_script:
  - "xpra --xvfb=\"Xorg +extension GLX -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :9"
script: "env DISPLAY=:9 rake test"
after_script:
  - "xpra stop :9"
  - "cat ~/.xpra/*"
